import { bannerFor, levelCode, type BulletinZoneRow } from '../lib/bulletin';

export interface BulletinDoc {
  refNo: string;
  issuedAt: string;
  sourceLabel: string;
  focus: string; // selected focus area at issue time
  overall: 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL';
  zones: number;
  severe: number;
  warnings: number;
  exposed: number;
  maxRain: number;
  maxPlace: string;
  anomalyCount: number;
  avgMoist: number;
  rows: BulletinZoneRow[];
  corridors: { corridor: string; name: string; status: string; bypass: string }[];
  directives: { to: string; points: string[] }[];
  communityCount: number;
}

// On-screen A4-style preview. The printed/PDF version is rendered by
// printBulletinHtml() into a clean standalone document (same content).
export default function Bulletin({ doc }: { doc: BulletinDoc }) {
  const banner = bannerFor(doc.overall);
  return (
    <div className="paper" id="bulletin-paper">
      <div className="bul-head">
        <div className="bul-govt">GOVERNMENT OF INDIA · MINISTRY OF DEVELOPMENT OF NORTH EASTERN REGION (MDoNER)</div>
        <h2>DAILY LANDSLIDE HAZARD ASSESSMENT &amp; EARLY WARNING BULLETIN</h2>
        <div className="bul-meta">
          <span><b>Ref:</b> {doc.refNo}</span>
          <span><b>Issued:</b> {doc.issuedAt}</span>
          <span><b>Weather sync:</b> {doc.sourceLabel}</span>
        </div>
        <div className="bul-banner" style={{ background: banner.color }}>{doc.overall === 'LOW' ? 'ADVISORY — ROUTINE WATCH' : `${banner.label} — LANDSLIDE THREAT LEVEL ${levelCode(doc.overall)}`}</div>
        <div className="bul-focus">🎯 Focus area: <b>{doc.focus}</b></div>
      </div>

      <div className="bul-sec">
        <h3>1 · Executive summary</h3>
        <p>Monitoring <b>{doc.zones} zones</b> across the North Eastern Region · <b>{doc.severe}</b> HIGH/CRITICAL · <b>{doc.warnings}</b> active warnings · <b>{doc.exposed.toLocaleString()}</b> people potentially exposed · {doc.communityCount} community reports on file.</p>
        <p className="muted-dark">Meteorology: peak 24h rainfall <b>{doc.maxRain} mm ({doc.maxPlace})</b> · {doc.anomalyCount} zones above seasonal baseline · mean soil-moisture estimate <b>{doc.avgMoist}%</b> (model-estimated, not sensor-measured).</p>
      </div>

      <div className="bul-sec">
        <h3>2 · Priority risk matrix</h3>
        <table className="bul-table">
          <thead><tr><th>#</th><th>District / Place (State)</th><th>Coords</th><th>Rain 24h / 7d</th><th>Slope · Soil</th><th>Index</th><th>Level</th><th>Primary driver</th></tr></thead>
          <tbody>{doc.rows.map((r, i) => (
            <tr key={r.zoneId}><td>{i + 1}</td><td>{r.district} / {r.place} ({r.state})</td><td>{r.lat.toFixed(2)}, {r.lon.toFixed(2)}</td><td>{r.rain24mm} / {r.rain7dmm} mm</td><td>{r.slopeDeg}° · {r.soil}</td><td><b>{r.score}</b></td><td>{r.level} ({levelCode(r.level)})</td><td>{r.reasons[0]}</td></tr>
          ))}</tbody>
        </table>
      </div>

      <div className="bul-sec">
        <h3>3 · Infrastructure &amp; lifeline impact</h3>
        <table className="bul-table">
          <thead><tr><th>Corridor</th><th>Segment</th><th>Status</th><th>Bypass if cut</th></tr></thead>
          <tbody>{doc.corridors.map((c, i) => <tr key={i}><td>{c.corridor}</td><td>{c.name}</td><td><b>{c.status}</b></td><td>{c.bypass}</td></tr>)}</tbody>
        </table>
        <p className="muted-dark">Critical assets in HIGH/CRITICAL zones: {doc.rows.filter(r => r.level === 'HIGH' || r.level === 'CRITICAL').map(r => `${r.place} (${r.infrastructure.slice(0, 2).join(', ')})`).join(' · ') || 'none'}.</p>
      </div>

      <div className="bul-sec">
        <h3>4 · Recommended operational directives</h3>
        {doc.directives.map(d => <div key={d.to}><p><b>{d.to}</b></p><ul>{d.points.map(p => <li key={p}>{p}</li>)}</ul></div>)}
      </div>

      <div className="bul-sec bul-sign">
        <h3>5 · Disclaimer &amp; authorisation</h3>
        <p className="muted-dark">Decision-support bulletin generated by the NER LandslideGuard AI engine. Risk indices are probabilistic estimates — they do not replace field verification by engineers and the District Disaster Management Authority. Simulated inputs are labelled as such in the data-source line.</p>
        <div className="bul-signrow"><div>Verified by (DDMA officer): ______________________</div><div>Date / Seal: ______________________</div></div>
      </div>
    </div>
  );
}

// Standalone print document: white A4, dark type, no app chrome.
export function printBulletinHtml(doc: BulletinDoc): string {
  const banner = bannerFor(doc.overall);
  const esc = (s: string | number) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const rows = doc.rows.map((r, i) => `<tr><td>${i + 1}</td><td>${esc(r.district)} / ${esc(r.place)} (${esc(r.state)})</td><td>${r.lat.toFixed(2)}, ${r.lon.toFixed(2)}</td><td>${r.rain24mm} / ${r.rain7dmm} mm</td><td>${r.slopeDeg}° · ${esc(r.soil)}</td><td><b>${r.score}</b></td><td>${r.level} (${levelCode(r.level)})</td><td>${esc((r.reasons && r.reasons[0]) || 'Baseline terrain susceptibility')}</td></tr>`).join('');
  const cors = doc.corridors.map(c => `<tr><td>${esc(c.corridor)}</td><td>${esc(c.name)}</td><td><b>${esc(c.status)}</b></td><td>${esc(c.bypass)}</td></tr>`).join('');
  const dirs = doc.directives.map(d => `<p><b>${esc(d.to)}</b></p><ul>${d.points.map(p => `<li>${esc(p)}</li>`).join('')}</ul>`).join('');
  const assets = doc.rows.filter(r => r.level === 'HIGH' || r.level === 'CRITICAL').map(r => `${esc(r.place)} (${r.infrastructure.slice(0, 2).map(esc).join(', ')})`).join(' · ') || 'none';
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(doc.refNo)} — Landslide Bulletin</title><style>
@page{size:A4 portrait;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#111827;background:#fff;margin:0;padding:0;font-size:11px;line-height:1.45}
.govt{font-size:10px;letter-spacing:.4px;color:#374151;text-align:center}.title{text-align:center}
h1{font-size:15px;margin:2px 0;text-align:center}h2{font-size:12px;margin:14px 0 6px;border-bottom:2px solid #111827;padding-bottom:3px}
.meta{display:flex;gap:16px;flex-wrap:wrap;font-size:10.5px;margin:6px 0;justify-content:center}
.focus{text-align:center;font-size:11px;margin:2px 0 0}
.banner{color:#fff;font-weight:700;text-align:center;padding:8px;margin:8px 0 0;font-size:13px;background:${banner.color};-webkit-print-color-adjust:exact;print-color-adjust:exact;page-break-inside:avoid;page-break-after:avoid}
table{width:100%;border-collapse:collapse;font-size:9px;margin:6px 0;table-layout:auto}th,td{border:1px solid #6b7280;padding:3px 4px;text-align:left;vertical-align:top;word-break:break-word}
th{background:#f3f4f6}thead{display:table-header-group}tr,section{page-break-inside:avoid}h2{page-break-after:avoid}
ul{margin:4px 0;padding-left:18px}
.sign{display:flex;gap:40px;margin-top:14px}.foot{font-size:9px;color:#4b5563;border-top:1px solid #9ca3af;margin-top:12px;padding-top:6px}
</style></head><body>
<div class="govt">GOVERNMENT OF INDIA · MINISTRY OF DEVELOPMENT OF NORTH EASTERN REGION (MDoNER)</div>
<h1 class="title">DAILY LANDSLIDE HAZARD ASSESSMENT &amp; EARLY WARNING BULLETIN</h1>
<div class="meta"><span><b>Ref:</b> ${esc(doc.refNo)}</span><span><b>Issued:</b> ${esc(doc.issuedAt)}</span><span><b>Weather sync:</b> ${esc(doc.sourceLabel)}</span></div>
<div class="banner">${doc.overall === 'LOW' ? 'ADVISORY — ROUTINE WATCH' : `${banner.label} — LANDSLIDE THREAT LEVEL ${levelCode(doc.overall)}`}</div>
<div class="focus">🎯 Focus area: <b>${esc(doc.focus || '—')}</b></div>
<section><h2>1 · Executive summary</h2><p>Monitoring <b>${doc.zones} zones</b> · <b>${doc.severe}</b> HIGH/CRITICAL · <b>${doc.warnings}</b> active warnings · <b>${doc.exposed.toLocaleString()}</b> people potentially exposed · ${doc.communityCount} community reports on file.</p>
<p>Meteorology: peak 24h rainfall <b>${doc.maxRain} mm (${esc(doc.maxPlace)})</b> · ${doc.anomalyCount} zones above seasonal baseline · mean soil-moisture estimate <b>${doc.avgMoist}%</b> (model-estimated, not sensor-measured).</p></section>
<section><h2>2 · Priority risk matrix</h2><table><thead><tr><th>#</th><th>District / Place (State)</th><th>Coords</th><th>Rain 24h / 7d</th><th>Slope · Soil</th><th>Index</th><th>Level</th><th>Primary driver</th></tr></thead><tbody>${rows}</tbody></table></section>
<section><h2>3 · Infrastructure &amp; lifeline impact</h2><table><thead><tr><th>Corridor</th><th>Segment</th><th>Status</th><th>Bypass if cut</th></tr></thead><tbody>${cors}</tbody></table>
<p>Critical assets in HIGH/CRITICAL zones: ${assets}.</p></section>
<section><h2>4 · Recommended operational directives</h2>${dirs}</section>
<section><h2>5 · Disclaimer &amp; authorisation</h2><p>Decision-support bulletin generated by the NER LandslideGuard AI engine. Risk indices are probabilistic estimates — they do not replace field verification by engineers and the District Disaster Management Authority. Simulated inputs are labelled as such in the data-source line.</p>
<div class="sign"><div>Verified by (DDMA officer): ______________________</div><div>Date / Seal: ______________________</div></div></section>
<div class="foot">${esc(doc.refNo)} · NER LandslideGuard · MDoNER SIH26001 prototype</div>
<script>window.onload=function(){setTimeout(function(){window.focus();window.print();},400);};</script></body></html>`;
}

export function openBulletinPrint(doc: BulletinDoc): boolean {
  const w = window.open('', '_blank', 'width=900,height=700');
  if (!w) return false;
  w.document.write(printBulletinHtml(doc));
  w.document.close();
  return true;
}
